## Data Visualization CA1
## Matthew Riddell - D00245674

### Data Cleaning Notebook

#### Import libraries

In [1]:
import pandas as pd
import numpy as np

#### File path and file loading

In [2]:
# Read each CSV
data_2023 = pd.read_csv("C:/Users/Matty/Documents/College Notes & Assignments/Year 5/Data Visualisation and Insight/CAs/CA1/Data-Vis-CA1/Matthew/Datasets/season_2223.csv")
data_2024 = pd.read_csv("C:/Users/Matty/Documents/College Notes & Assignments/Year 5/Data Visualisation and Insight/CAs/CA1/Data-Vis-CA1/Matthew/Datasets/season_2324.csv")
data_2025 = pd.read_csv("C:/Users/Matty/Documents/College Notes & Assignments/Year 5/Data Visualisation and Insight/CAs/CA1/Data-Vis-CA1/Matthew/Datasets/season_2425.csv")

#### Season Column

In [3]:
data_2023["Season"] = "2020 / 2021"
data_2024["Season"] = "2021 / 2022"
data_2025["Season"] = "2022 / 2023"

#### Merging all three datasets into one

In [4]:
# Combine datasets
combined_data = pd.concat([data_2023, data_2024, data_2025], ignore_index=True)

#### Display first 30 rows

In [5]:
combined_data.head(30)

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,...,AST,HF,AF,HC,AC,HY,AY,HR,AR,Season
0,05/08/22,Crystal Palace,Arsenal,0,2,A,0,1,A,A Taylor,...,2,16,11,3,5,1,2,0,0,2020 / 2021
1,06/08/22,Fulham,Liverpool,2,2,D,1,0,H,A Madley,...,4,7,9,4,4,2,0,0,0,2020 / 2021
2,06/08/22,Bournemouth,Aston Villa,2,0,H,1,0,H,P Bankes,...,2,18,16,5,5,3,3,0,0,2020 / 2021
3,06/08/22,Leeds,Wolves,2,1,H,1,1,D,R Jones,...,6,13,9,6,4,2,0,0,0,2020 / 2021
4,06/08/22,Newcastle,Nott'm Forest,2,0,H,0,0,D,S Hooper,...,0,9,14,11,1,0,3,0,0,2020 / 2021
5,06/08/22,Tottenham,Southampton,4,1,H,2,1,H,A Marriner,...,2,11,6,10,2,3,0,0,0,2020 / 2021
6,06/08/22,Everton,Chelsea,0,1,A,0,1,A,C Pawson,...,6,14,11,4,16,3,2,0,0,2020 / 2021
7,07/08/22,Leicester,Brentford,2,2,D,1,0,H,J Gillett,...,3,6,5,5,6,0,0,0,0,2020 / 2021
8,07/08/22,Man United,Brighton,1,2,A,0,2,A,P Tierney,...,4,7,12,6,2,4,1,0,0,2020 / 2021
9,07/08/22,West Ham,Man City,0,2,A,0,1,A,M Oliver,...,2,8,4,1,4,0,1,0,0,2020 / 2021
10,13/08/22,Aston Villa,Everton,2,1,H,1,0,H,M Oliver,...,4,9,7,5,8,4,1,0,0,2020 / 2021
11,13/08/22,Arsenal,Leicester,4,2,H,2,0,H,D England,...,2,15,9,6,2,1,1,0,0,2020 / 2021
12,13/08/22,Brighton,Newcastle,0,0,D,0,0,D,G Scott,...,1,8,6,7,3,2,3,0,0,2020 / 2021
13,13/08/22,Man City,Bournemouth,4,0,H,3,0,H,D Coote,...,1,9,9,11,1,0,3,0,0,2020 / 2021
14,13/08/22,Southampton,Leeds,2,2,D,0,0,D,T Harrington,...,5,10,12,2,5,1,3,0,0,2020 / 2021
15,13/08/22,Wolves,Fulham,0,0,D,0,0,D,J Brooks,...,3,7,14,5,3,3,3,0,0,2020 / 2021
16,13/08/22,Brentford,Man United,4,0,H,4,0,H,S Attwell,...,4,6,15,8,2,0,4,0,0,2020 / 2021
17,14/08/22,Nott'm Forest,West Ham,1,0,H,1,0,H,R Jones,...,5,10,11,6,7,4,1,0,0,2020 / 2021
18,14/08/22,Chelsea,Tottenham,2,2,D,1,0,H,A Taylor,...,5,9,9,8,5,3,0,0,0,2020 / 2021
19,15/08/22,Liverpool,Crystal Palace,1,1,D,0,1,A,P Tierney,...,3,7,8,4,2,2,4,1,0,2020 / 2021
20,20/08/22,Tottenham,Wolves,1,0,H,0,0,D,S Hooper,...,3,10,8,8,6,2,2,0,0,2020 / 2021
21,20/08/22,Crystal Palace,Aston Villa,3,1,H,1,1,D,A Madley,...,5,16,14,4,2,2,1,0,0,2020 / 2021
22,20/08/22,Everton,Nott'm Forest,1,1,D,0,0,D,A Marriner,...,5,6,9,6,2,3,2,0,0,2020 / 2021
23,20/08/22,Fulham,Brentford,3,2,H,2,1,H,P Bankes,...,5,13,7,6,3,3,2,0,0,2020 / 2021
24,20/08/22,Leicester,Southampton,1,2,A,0,0,D,M Salisbury,...,3,11,15,2,5,2,3,0,0,2020 / 2021
25,20/08/22,Bournemouth,Arsenal,0,3,A,0,2,A,C Pawson,...,6,12,10,3,4,2,1,0,0,2020 / 2021
26,21/08/22,Leeds,Chelsea,3,0,H,2,0,H,S Attwell,...,3,16,15,4,6,0,1,0,1,2020 / 2021
27,21/08/22,West Ham,Brighton,0,2,A,0,1,A,A Taylor,...,2,10,7,5,4,2,0,0,0,2020 / 2021
28,21/08/22,Newcastle,Man City,3,3,D,2,1,H,J Gillett,...,10,14,7,5,5,4,2,0,0,2020 / 2021
29,22/08/22,Man United,Liverpool,2,1,H,1,0,H,M Oliver,...,5,11,7,6,8,3,1,0,0,2020 / 2021

#### Check basic information about the dataset

In [6]:
print("Information about the dataset:")
print(combined_data.info())

Information about the dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1140 entries, 0 to 1139
Data columns (total 23 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      1140 non-null   object
 1   HomeTeam  1140 non-null   object
 2   AwayTeam  1140 non-null   object
 3   FTHG      1140 non-null   int64
 4   FTAG      1140 non-null   int64
 5   FTR       1140 non-null   object
 6   HTHG      1140 non-null   int64
 7   HTAG      1140 non-null   int64
 8   HTR       1140 non-null   object
 9   Referee   1140 non-null   object
 10  HS        1140 non-null   int64
 11  AS        1140 non-null   int64
 12  HST       1140 non-null   int64
 13  AST       1140 non-null   int64
 14  HF        1140 non-null   int64
 15  AF        1140 non-null   int64
 16  HC        1140 non-null   int64
 17  AC        1140 non-null   int64
 18  HY        1140 non-null   int64
 19  AY        1140 non-null   int64
 20  HR        1140 non-null   int64
 21  AR        1140 non-null   int64
 22  Season    1140 non-null   object
dtypes: int64(16), object(7)
memory usage: 205.0+ KB
None

#### Display Column Names

In [7]:
print("Original column names:")
print(combined_data.columns)

Original column names:
Index(['Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG', 'HTAG',
       'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC',
       'HY', 'AY', 'HR', 'AR', 'Season'],
      dtype='object')

#### Check for missing values in the dataset

In [8]:
print("Number of missing values in each column:")
print(combined_data.isna().sum())

Number of missing values in each column:
Date        0
HomeTeam    0
AwayTeam    0
FTHG        0
FTAG        0
FTR         0
HTHG        0
HTAG        0
HTR         0
Referee     0
HS          0
AS          0
HST         0
AST         0
HF          0
AF          0
HC          0
AC          0
HY          0
AY          0
HR          0
AR          0
Season      0
dtype: int64

#### Show total missing values across the dataset

In [9]:
total_missing = combined_data.isna().sum().sum()
print("Total missing values in the dataset:", total_missing)

Total missing values in the dataset: 0

#### List containing possible missing values in the columns

In [10]:
nonsense_values = ["?", "error", "missing", "Missing", "NaN", "nan", "N/A", "n/a", "--", " "]

#### Checking the nonsense_values list across the dataset

This loop goes through the dataset while checking the nonsense values list, 
if a value from the list appears in a column, 
it will increase the count by 1, 
at the end of the loop it will then print out a total per column of nonsense values counted across the dataset.

In [11]:
print("Checking for nonsense values:")
for col in combined_data.columns:
    count = combined_data[col].isin(nonsense_values).sum() 
    if count > 0:
        print(col, "has", count, "nonsense values")

Checking for nonsense values:

#### Replace all nonsense values with NaN

In [12]:
combined_data = combined_data.replace(nonsense_values, np.nan)

#### Check again for missing values after replacement

In [13]:
print("Number of missing values after cleaning nonsense values:")
print(combined_data.isna().sum())

Number of missing values after cleaning nonsense values:
Date        0
HomeTeam    0
AwayTeam    0
FTHG        0
FTAG        0
FTR         0
HTHG        0
HTAG        0
HTR         0
Referee     0
HS          0
AS          0
HST         0
AST         0
HF          0
AF          0
HC          0
AC          0
HY          0
AY          0
HR          0
AR          0
Season      0
dtype: int64

#### List of columns with numerical data

In [14]:
numeric_columns = ['FTHG', 'FTAG', 
                   'HTHG', 'HTAG', 'HS',
                   'AS', 'HST', 'AST', 
                   'HF', 'AF', 'HC', 'AC', 'HY', 'AY', 'HR', 'AR']

#### Fill missing numeric values with the mean of each column / dropping rows with missing values

In [15]:
for col in numeric_columns:
    if col in combined_data.columns:
        combined_data[col] = pd.to_numeric(combined_data[col], errors='coerce')
        ## mean_value = combined_data[col].mean() 
        ## combined_data[col] = combined_data[col].fillna(mean_value)

print("Shape before dropping rows with missing values:", combined_data.shape)
combined_data = combined_data.dropna()
print("Shape after dropping rows with missing values:", combined_data.shape)

print("Missing values after filling numeric columns with mean:")
print(combined_data.isna().sum())

Shape before dropping rows with missing values: (1140, 23)
Shape after dropping rows with missing values: (1140, 23)
Missing values after filling numeric columns with mean:
Date        0
HomeTeam    0
AwayTeam    0
FTHG        0
FTAG        0
FTR         0
HTHG        0
HTAG        0
HTR         0
Referee     0
HS          0
AS          0
HST         0
AST         0
HF          0
AF          0
HC          0
AC          0
HY          0
AY          0
HR          0
AR          0
Season      0
dtype: int64

#### Checking the data again

In [16]:
combined_data.head(20)

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,...,AST,HF,AF,HC,AC,HY,AY,HR,AR,Season
0,05/08/22,Crystal Palace,Arsenal,0,2,A,0,1,A,A Taylor,...,2,16,11,3,5,1,2,0,0,2020 / 2021
1,06/08/22,Fulham,Liverpool,2,2,D,1,0,H,A Madley,...,4,7,9,4,4,2,0,0,0,2020 / 2021
2,06/08/22,Bournemouth,Aston Villa,2,0,H,1,0,H,P Bankes,...,2,18,16,5,5,3,3,0,0,2020 / 2021
3,06/08/22,Leeds,Wolves,2,1,H,1,1,D,R Jones,...,6,13,9,6,4,2,0,0,0,2020 / 2021
4,06/08/22,Newcastle,Nott'm Forest,2,0,H,0,0,D,S Hooper,...,0,9,14,11,1,0,3,0,0,2020 / 2021
5,06/08/22,Tottenham,Southampton,4,1,H,2,1,H,A Marriner,...,2,11,6,10,2,3,0,0,0,2020 / 2021
6,06/08/22,Everton,Chelsea,0,1,A,0,1,A,C Pawson,...,6,14,11,4,16,3,2,0,0,2020 / 2021
7,07/08/22,Leicester,Brentford,2,2,D,1,0,H,J Gillett,...,3,6,5,5,6,0,0,0,0,2020 / 2021
8,07/08/22,Man United,Brighton,1,2,A,0,2,A,P Tierney,...,4,7,12,6,2,4,1,0,0,2020 / 2021
9,07/08/22,West Ham,Man City,0,2,A,0,1,A,M Oliver,...,2,8,4,1,4,0,1,0,0,2020 / 2021
10,13/08/22,Aston Villa,Everton,2,1,H,1,0,H,M Oliver,...,4,9,7,5,8,4,1,0,0,2020 / 2021
11,13/08/22,Arsenal,Leicester,4,2,H,2,0,H,D England,...,2,15,9,6,2,1,1,0,0,2020 / 2021
12,13/08/22,Brighton,Newcastle,0,0,D,0,0,D,G Scott,...,1,8,6,7,3,2,3,0,0,2020 / 2021
13,13/08/22,Man City,Bournemouth,4,0,H,3,0,H,D Coote,...,1,9,9,11,1,0,3,0,0,2020 / 2021
14,13/08/22,Southampton,Leeds,2,2,D,0,0,D,T Harrington,...,5,10,12,2,5,1,3,0,0,2020 / 2021
15,13/08/22,Wolves,Fulham,0,0,D,0,0,D,J Brooks,...,3,7,14,5,3,3,3,0,0,2020 / 2021
16,13/08/22,Brentford,Man United,4,0,H,4,0,H,S Attwell,...,4,6,15,8,2,0,4,0,0,2020 / 2021
17,14/08/22,Nott'm Forest,West Ham,1,0,H,1,0,H,R Jones,...,5,10,11,6,7,4,1,0,0,2020 / 2021
18,14/08/22,Chelsea,Tottenham,2,2,D,1,0,H,A Taylor,...,5,9,9,8,5,3,0,0,0,2020 / 2021
19,15/08/22,Liverpool,Crystal Palace,1,1,D,0,1,A,P Tierney,...,3,7,8,4,2,2,4,1,0,2020 / 2021

#### Checking for outliers

In [17]:
print("Detecting outliers using IQR method:\n")

for col in numeric_columns:
    if col in combined_data.columns:
        Q1 = combined_data[col].quantile(0.25) # https://www.w3schools.com/Python/pandas/ref_df_quantile.asp
        Q3 = combined_data[col].quantile(0.75) # https://www.w3schools.com/Python/pandas/ref_df_quantile.asp
        IQR = Q3 - Q1
        lower_limit = Q1 - 1.5 * IQR
        upper_limit = Q3 + 1.5 * IQR
        
        outliers = combined_data[(combined_data[col] < lower_limit) | (combined_data[col] > upper_limit)]
        print(col, "has", outliers.shape[0], "outliers")

Detecting outliers using IQR method:

FTHG has 117 outliers
FTAG has 7 outliers
HTHG has 50 outliers
HTAG has 30 outliers
HS has 14 outliers
AS has 16 outliers
HST has 5 outliers
AST has 57 outliers
HF has 2 outliers
AF has 6 outliers
HC has 5 outliers
AC has 54 outliers
HY has 1 outliers
AY has 4 outliers
HR has 67 outliers
AR has 66 outliers

#### clipping extreme outliers

I decided to keep the outliers in as i want to visualise the data as is

In [18]:
"""for col in numeric_columns:
    if col in combined_data.columns:
        Q1 = combined_data[col].quantile(0.25) # https://www.w3schools.com/Python/pandas/ref_df_quantile.asp
        Q3 = combined_data[col].quantile(0.75) # https://www.w3schools.com/Python/pandas/ref_df_quantile.asp
        IQR = Q3 - Q1
        lower_limit = Q1 - 1.5 * IQR
        upper_limit = Q3 + 1.5 * IQR
        
        mean_before = combined_data[col].mean() # Mean before clipping
        
        combined_data[col] = combined_data[col].clip(lower=lower_limit, upper=upper_limit) # Clip extreme outliers https://www.w3resource.com/pandas/dataframe/dataframe-clip.php
        
        mean_after = combined_data[col].mean() # Mean after clipping
        
        print(col, ": mean before =", round(mean_before, 2), ", mean after =", round(mean_after, 2)) """

'for col in numeric_columns:\n    if col in combined_data.columns:\n        Q1 = combined_data[col].quantile(0.25) # https://www.w3schools.com/Python/pandas/ref_df_quantile.asp\n        Q3 = combined_data[col].quantile(0.75) # https://www.w3schools.com/Python/pandas/ref_df_quantile.asp\n        IQR = Q3 - Q1\n        lower_limit = Q1 - 1.5 * IQR\n        upper_limit = Q3 + 1.5 * IQR\n        \n        mean_before = combined_data[col].mean() # Mean before clipping\n        \n        combined_data[col] = combined_data[col].clip(lower=lower_limit, upper=upper_limit) # Clip extreme outliers https://www.w3resource.com/pandas/dataframe/dataframe-clip.php\n        \n        mean_after = combined_data[col].mean() # Mean after clipping\n        \n        print(col, ": mean before =", round(mean_before, 2), ", mean after =", round(mean_after, 2)) '

#### Convert to datetime object

In [19]:
combined_data['Date'] = pd.to_datetime(combined_data['Date'], format='%d/%m/%y')

#### sort by date

In [20]:
combined_data = combined_data.sort_values(by='Date')

In [21]:
print("First 5 dates after sorting:")
print(combined_data['Date'].head())

print("Last 5 dates after sorting:")
print(combined_data['Date'].tail())

First 5 dates after sorting:
0   2022-08-05
1   2022-08-06
2   2022-08-06
3   2022-08-06
4   2022-08-06
Name: Date, dtype: datetime64[ns]
Last 5 dates after sorting:
1132   2025-05-25
1131   2025-05-25
1130   2025-05-25
1133   2025-05-25
1139   2025-05-25
Name: Date, dtype: datetime64[ns]

#### Check how many missing values are in each column

In [22]:
print("Missing values per column:")
print(combined_data.isna().sum())

Missing values per column:
Date        0
HomeTeam    0
AwayTeam    0
FTHG        0
FTAG        0
FTR         0
HTHG        0
HTAG        0
HTR         0
Referee     0
HS          0
AS          0
HST         0
AST         0
HF          0
AF          0
HC          0
AC          0
HY          0
AY          0
HR          0
AR          0
Season      0
dtype: int64

#### Find columns that are completely empty (all values are NaN)

In [23]:
empty_columns = combined_data.columns[combined_data.isna().sum() == len(combined_data)]

In [24]:
print("Empty columns found:")
print(empty_columns)

Empty columns found:
Index([], dtype='object')

#### Drop empty columns

In [25]:
combined_data = combined_data.drop(columns=empty_columns)

#### Display column names

In [26]:
print("Original column names:")
print(combined_data.columns)

Original column names:
Index(['Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG', 'HTAG',
       'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC',
       'HY', 'AY', 'HR', 'AR', 'Season'],
      dtype='object')

#### Renaming Column Names
I rename the column names so they are more readable and so that they will be easier to use when I use Power BI / Tablaeu

In [27]:
combined_data = combined_data.rename(columns={
    'Date': 'Match Date',
    'HomeTeam': 'Home Team',
    'AwayTeam': 'Away Team',
    'FTHG': 'Full Time Home Goals',
    'FTAG': 'Full Time Away Goals',
    'FTR': 'Full Time Result',
    'HTHG': 'Half Time Home Goals',
    'HTAG': 'Half Time Away Goals',
    'HTR': 'Half Time Result',
    'Referee': 'Match Referee',
    'HS': 'Home Team Shots',
    'AS': 'Away Team Shots',
    'HST': 'Home Team Shots on Target',
    'AST': 'Away Team Shots on Target',
    'HF': 'Home Team Fouls',
    'AF': 'Away Team Fouls',
    'HC': 'Home Team Corners',
    'AC': 'Away Team Corners',
    'HY': 'Home Team Yellow Cards',
    'AY': 'Away Team Yellow Cards',
    'HR': 'Home Team Red Cards',
    'AR': 'Away Team Red Cards',
    'Season': 'Season'
})

#### Display renamed column names

In [28]:
print("New column names after renaming:")
print(combined_data.columns)

New column names after renaming:
Index(['Match Date', 'Home Team', 'Away Team', 'Full Time Home Goals',
       'Full Time Away Goals', 'Full Time Result', 'Half Time Home Goals',
       'Half Time Away Goals', 'Half Time Result', 'Match Referee',
       'Home Team Shots', 'Away Team Shots', 'Home Team Shots on Target',
       'Away Team Shots on Target', 'Home Team Fouls', 'Away Team Fouls',
       'Home Team Corners', 'Away Team Corners', 'Home Team Yellow Cards',
       'Away Team Yellow Cards', 'Home Team Red Cards', 'Away Team Red Cards',
       'Season'],
      dtype='object')

#### Display new dataset shape

In [29]:
print("Shape of the dataset after removing empty columns:", combined_data.shape)

Shape of the dataset after removing empty columns: (1140, 23)

#### Save the cleaned dataset to a new CSV file

In [30]:
combined_data.to_csv("cleaned_season_data.csv", index=False) # https://www.geeksforgeeks.org/pandas/saving-a-pandas-dataframe-as-a-csv/

print("Cleaned dataset has been saved as 'cleaned_season_data.csv'.")

Cleaned dataset has been saved as 'cleaned_season_data.csv'.

#### Quick check of the final dataset

In [31]:
print("Final dataset shape:", combined_data.shape)
print("First 5 rows of the final cleaned dataset:")
print(combined_data.head())

Final dataset shape: (1140, 23)
First 5 rows of the final cleaned dataset:
  Match Date       Home Team      Away Team  Full Time Home Goals  \
0 2022-08-05  Crystal Palace        Arsenal                     0
1 2022-08-06          Fulham      Liverpool                     2
2 2022-08-06     Bournemouth    Aston Villa                     2
3 2022-08-06           Leeds         Wolves                     2
4 2022-08-06       Newcastle  Nott'm Forest                     2

   Full Time Away Goals Full Time Result  Half Time Home Goals  \
0                     2                A                     0
1                     2                D                     1
2                     0                H                     1
3                     1                H                     1
4                     0                H                     0

   Half Time Away Goals Half Time Result Match Referee  ...  \
0                     1                A      A Taylor  ...
1                     0                H      A Madley  ...
2                     0                H      P Bankes  ...
3                     1                D       R Jones  ...
4                     0                D      S Hooper  ...

   Away Team Shots on Target  Home Team Fouls  Away Team Fouls  \
0                          2               16               11
1                          4                7                9
2                          2               18               16
3                          6               13                9
4                          0                9               14

   Home Team Corners  Away Team Corners  Home Team Yellow Cards  \
0                  3                  5                       1
1                  4                  4                       2
2                  5                  5                       3
3                  6                  4                       2
4                 11                  1                       0

   Away Team Yellow Cards  Home Team Red Cards  Away Team Red Cards  \
0                       2                    0                    0
1                       0                    0                    0
2                       3                    0                    0
3                       0                    0                    0
4                       3                    0                    0

        Season
0  2020 / 2021
1  2020 / 2021
2  2020 / 2021
3  2020 / 2021
4  2020 / 2021

[5 rows x 23 columns]